/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   g++.exe -c -w -fpermissive -DSDL_MAIN_HANDLED -O3 -fno-strict-aliasing  -IC:\App\native-toolchain\nim-0.10.2\lib -o c:\users\nigahachi\desktop\projectc++\nim\nimcache\strutils.o c:\users\nigahachi\desktop\projectc++\nim\nimcache\strutils.cpp */
#define NIM_INTBITS 32
#include "nimbase.h"
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsDatInit)(void) {
}

