/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -O3 -fno-strict-aliasing  -IC:\App\native-toolchain\nim-0.10.2\lib -o c:\users\nigahachi\desktop\projectc\nim\nimcache\system.o c:\users\nigahachi\desktop\projectc\nim\nimcache\system.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <io.h>

#include <fcntl.h>

#include <windows.h>

#include <stdio.h>

#include <stdlib.h>

#include <setjmp.h>

#include <string.h>

#include <signal.h>
typedef struct Exception Exception;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tavlnode27008 tavlnode27008;
typedef struct tgcheap46816 tgcheap46816;
typedef struct tcellseq44749 tcellseq44749;
typedef struct tcell44733 tcell44733;
typedef struct tcellset44745 tcellset44745;
typedef struct tpagedesc44741 tpagedesc44741;
typedef struct tmemregion27010 tmemregion27010;
typedef struct tsmallchunk26240 tsmallchunk26240;
typedef struct tllchunk27004 tllchunk27004;
typedef struct tbigchunk26242 tbigchunk26242;
typedef struct tintset26217 tintset26217;
typedef struct ttrunk26213 ttrunk26213;
typedef struct tgcstat46814 tgcstat46814;
typedef struct tbasechunk26238 tbasechunk26238;
typedef struct tfreecell26230 tfreecell26230;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct TSafePoint TSafePoint;
typedef struct TNimObject TNimObject;
typedef N_NIMCALL_PTR(NIM_BOOL, TY8221) (Exception* e);
typedef N_NIMCALL_PTR(NIM_BOOL, TY8226) (Exception* e);
typedef N_NIMCALL_PTR(void, TY8231) (void);
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
typedef tavlnode27008* TY27014[2];
struct  tavlnode27008  {
TY27014 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tcellseq44749  {
NI Len;
NI Cap;
tcell44733** D;
};
struct  tcellset44745  {
NI Counter;
NI Max;
tpagedesc44741* Head;
tpagedesc44741** Data;
};
typedef tsmallchunk26240* TY27022[512];
typedef ttrunk26213* ttrunkbuckets26215[256];
struct  tintset26217  {
ttrunkbuckets26215 Data;
};
struct  tmemregion27010  {
NI Minlargeobj;
NI Maxlargeobj;
TY27022 Freesmallchunks;
tllchunk27004* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26242* Freechunkslist;
tintset26217 Chunkstarts;
tavlnode27008* Root;
tavlnode27008* Deleted;
tavlnode27008* Last;
tavlnode27008* Freeavlnodes;
};
struct  tgcstat46814  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap46816  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq44749 Zct;
tcellseq44749 Decstack;
tcellset44745 Cycleroots;
tcellseq44749 Tempstack;
NI Recgclock;
tmemregion27010 Region;
tgcstat46814 Stat;
};
struct  tbasechunk26238  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26240  {
  tbasechunk26238 Sup;
tsmallchunk26240* Next;
tsmallchunk26240* Prev;
tfreecell26230* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tbigchunk26242  {
  tbasechunk26238 Sup;
tbigchunk26242* Next;
tbigchunk26242* Prev;
NI Align;
NF Data;
};
typedef NI TY26220[16];
struct  ttrunk26213  {
ttrunk26213* Next;
NI Key;
TY26220 Bits;
};
struct  tllchunk27004  {
NI Size;
NI Acc;
tllchunk27004* Next;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  tfreecell26230  {
tfreecell26230* Next;
NI Zerofield;
};
typedef N_NIMCALL_PTR(void, TY16001) (NimStringDesc* msg);
typedef TFrame* TY16601[128];
struct  tcell44733  {
NI Refcount;
TNimType* Typ;
};
struct  tpagedesc44741  {
tpagedesc44741* Next;
NI Key;
TY26220 Bits;
};
typedef N_NIMCALL_PTR(void, TFinalizer) (void* self);
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY14809;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY14809 raiseAction;
};
static N_INLINE(void, initallocator_9401)(void);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
N_NIMCALL(void, initgc_9201)(void);
N_NIMCALL(void, init_44847)(tcellseq44749* s, NI cap);
N_NOCONV(void*, alloc0_5817)(NI size);
N_NIMCALL(void*, alloc0_43419)(tmemregion27010* allocator, NI size);
N_NIMCALL(void*, alloc_43234)(tmemregion27010* allocator, NI size);
N_NIMCALL(void*, rawalloc_34146)(tmemregion27010* a, NI requestedsize);
static N_INLINE(NI, roundup_26270)(NI x, NI v);
N_NIMCALL(tsmallchunk26240*, getsmallchunk_33628)(tmemregion27010* a);
N_NIMCALL(tbigchunk26242*, getbigchunk_32820)(tmemregion27010* a, NI size);
static N_INLINE(void, listremove_30603)(tbigchunk26242** head_30609, tbigchunk26242* c_30612);
N_NIMCALL(void, splitchunk_32615)(tmemregion27010* a, tbigchunk26242* c, NI size);
static N_INLINE(void, updateprevsize_29691)(tmemregion27010* a, tbigchunk26242* c, NI prevsize);
static N_INLINE(NIM_BOOL, isaccessible_29621)(tmemregion27010* a, void* p);
N_NIMCALL(NIM_BOOL, contains_28595)(tintset26217* s, NI key);
N_NIMCALL(ttrunk26213*, intsetget_28524)(tintset26217* t, NI key);
static N_INLINE(NI, pageindex_28938)(void* p);
N_NIMCALL(void, incl_28624)(tmemregion27010* a, tintset26217* s, NI key);
N_NIMCALL(ttrunk26213*, intsetput_28560)(tmemregion27010* a, tintset26217* t, NI key);
N_NIMCALL(void*, llalloc_27259)(tmemregion27010* a, NI size);
static N_INLINE(void*, osallocpages_26023)(NI size);
N_NOINLINE(void, raiseoutofmem_25659)(void);
static N_INLINE(void, inccurrmem_27205)(tmemregion27010* a, NI bytes);
static N_INLINE(NI, pageindex_28930)(tbasechunk26238* c);
static N_INLINE(void, listadd_31831)(tbigchunk26242** head_31837, tbigchunk26242* c_31840);
N_NIMCALL(tbigchunk26242*, requestoschunks_28956)(tmemregion27010* a, NI size);
static N_INLINE(void, listadd_35005)(tsmallchunk26240** head_35011, tsmallchunk26240* c_35014);
static N_INLINE(void, listremove_37803)(tsmallchunk26240** head_37809, tsmallchunk26240* c_37812);
N_NIMCALL(void, add_28224)(tmemregion27010* a, tavlnode27008** t, NI key, NI upperbound);
N_NIMCALL(tavlnode27008*, allocavlnode_27436)(tmemregion27010* a, NI key, NI upperbound);
N_NIMCALL(void, skew_28196)(tavlnode27008** t);
N_NIMCALL(void, split_28204)(tavlnode27008** t);
N_NIMCALL(void, init_44868)(tcellset44745* s);
N_NOCONV(void, signalHandler)(int sig);
N_NIMCALL(void, showerrormessage_16209)(NCSTRING data);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, toNimStr)(NCSTRING str, NI len);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void*, rawnewobj_54604)(TNimType* typ, NI size, tgcheap46816* gch);
N_NIMCALL(void, collectct_48810)(tgcheap46816* gch);
static N_INLINE(NI, getoccupiedmem_44668)(tmemregion27010* a);
N_NIMCALL(void, collectctbody_71419)(tgcheap46816* gch);
N_NOINLINE(NI, stacksize_68810)(void);
static N_INLINE(void, prepareforinteriorpointerchecking_42082)(tmemregion27010* a);
N_NIMCALL(NI, lowgauge_28018)(tavlnode27008* n);
N_NIMCALL(NI, highgauge_28049)(tavlnode27008* n);
N_CDECL(void, markstackandregisters_69040)(tgcheap46816* gch);
static N_INLINE(void, gcmark_67446)(tgcheap46816* gch, void* p);
static N_INLINE(tcell44733*, usrtocell_48446)(void* usr);
N_NIMCALL(void*, interiorallocatedptr_42089)(tmemregion27010* a, void* p);
static N_INLINE(tbasechunk26238*, pageaddr_28946)(void* p);
static N_INLINE(NIM_BOOL, chunkunused_28810)(tbasechunk26238* c);
static N_INLINE(NIM_BOOL, issmallchunk_28799)(tbasechunk26238* c);
N_NIMCALL(tavlnode27008*, inrange_28129)(tavlnode27008* root, NI key);
static N_INLINE(void, add_44821)(tcellseq44749* s, tcell44733* c);
N_NOCONV(void*, alloc_5801)(NI size);
N_NOCONV(void, dealloc_5848)(void* p);
N_NIMCALL(void, dealloc_43428)(tmemregion27010* allocator, void* p);
N_NIMCALL(void, rawdealloc_40423)(tmemregion27010* a, void* p);
N_NIMCALL(void, freebigchunk_29806)(tmemregion27010* a, tbigchunk26242* c_29810);
N_NIMCALL(void, excl_28638)(tintset26217* s, NI key);
N_NIMCALL(void, freeoschunks_29410)(tmemregion27010* a, void* p, NI size);
static N_INLINE(void, osdeallocpages_26031)(void* p, NI size);
static N_INLINE(void, deccurrmem_27225)(tmemregion27010* a, NI bytes);
N_NIMCALL(void, del_28404)(tmemregion27010* a, tavlnode27008** t, NI x);
static N_INLINE(void, deallocavlnode_28006)(tmemregion27010* a, tavlnode27008* n);
N_NIMCALL(void, markthreadstacks_68006)(tgcheap46816* gch);
N_NIMCALL(NIM_BOOL, collectzct_66812)(tgcheap46816* gch);
static N_INLINE(NIM_BOOL, canbecycleroot_48467)(tcell44733* c);
N_NIMCALL(void, excl_45502)(tcellset44745* s, tcell44733* cell);
N_NIMCALL(tpagedesc44741*, cellsetget_44920)(tcellset44745 t, NI key);
static N_INLINE(NI, nexttry_44912)(NI h, NI maxhash);
N_NIMCALL(void, preparedealloc_49008)(tcell44733* cell);
static N_INLINE(void*, celltousr_48425)(tcell44733* cell);
N_NIMCALL(void, forallchildren_48817)(tcell44733* cell, NU8 op);
N_NIMCALL(void, forallchildrenaux_48825)(void* dest, TNimType* mt, NU8 op);
N_NIMCALL(void, dooperation_48821)(void* p, NU8 op);
static N_INLINE(void, decref_50404)(tcell44733* c);
static N_INLINE(void, rtladdzct_50004)(tcell44733* c);
N_NOINLINE(void, addzct_48417)(tcellseq44749* s, tcell44733* c);
static N_INLINE(void, rtladdcycleroot_49229)(tcell44733* c);
N_NOINLINE(void, incl_45471)(tcellset44745* s, tcell44733* cell);
N_NIMCALL(tpagedesc44741*, cellsetput_45266)(tcellset44745* t, NI key);
N_NIMCALL(void, cellsetenlarge_45212)(tcellset44745* t);
N_NIMCALL(void, cellsetrawinsert_44954)(tcellset44745 t, tpagedesc44741** data, tpagedesc44741* desc);
N_NIMCALL(void, markgray_64005)(tcell44733* s);
N_NIMCALL(void, scan_64404)(tcell44733* s);
N_NIMCALL(void, scanblack_64204)(tcell44733* s);
N_NIMCALL(void, collectwhite_64604)(tcell44733* s);
N_NIMCALL(NIM_BOOL, contains_45423)(tcellset44745 s, tcell44733* cell);
N_NIMCALL(void, freecycliccell_63227)(tgcheap46816* gch, tcell44733* c);
N_NIMCALL(void, forallslotsaux_53008)(void* dest, TNimNode* n, NU8 op);
N_NIMCALL(TNimNode*, selectbranch_25410)(void* aa, TNimNode* n);
N_NIMCALL(NI, getdiscriminant_25136)(void* aa, TNimNode* n);
N_NIMCALL(void, collectcycles_67045)(tgcheap46816* gch);
N_NIMCALL(void, markroots_64805)(tgcheap46816* gch);
N_NIMCALL(void, collectroots_67001)(tgcheap46816* gch);
N_NIMCALL(void, cellsetreset_53001)(tcellset44745* s);
N_NIMCALL(void, deinit_44879)(tcellset44745* s);
N_NIMCALL(NI, getoccupiedmem_6495)(void);
N_NIMCALL(NI, gettotalmem_6499)(void);
N_NIMCALL(NI, getfreemem_6497)(void);
N_NIMCALL(void, unmarkstackandregisters_71211)(tgcheap46816* gch);
static N_INLINE(void, addnewobjtozct_54090)(tcell44733* res, tgcheap46816* gch);
N_NIMCALL(void, writetostderr_16201)(NCSTRING msg);
N_NIMCALL(void, write_12877)(FILE* f, NCSTRING c);
N_NIMCALL(void, registersignalhandler_19808)(void);
N_NIMCALL(NI, getRefcount)(void* p);
STRING_LITERAL(TMP2, "out of memory", 13);
NI nim_program_result;
TY8221 globalraisehook_8225;
TY8226 localraisehook_8230;
TY8231 outofmemhook_8233;
TNimType strdesc_9804;
TY16001 errormessagewriter_16004;
TFrame* frameptr_16242;
TSafePoint* exchandler_16243;
Exception* currexception_16245;
TY16601 tempframes_16604;
tavlnode27008 bottomdata_27038;
tavlnode27008* bottom_27039;
tgcheap46816 gch_46844;
NIM_BOOL localgcinitialized_52804;
NIM_CHAR decimalpoint_75660;

static N_INLINE(void, initallocator_9401)(void) {
	bottom_27039 = (&bottomdata_27038);
	(*bottom_27039).Link[(0)- 0] = bottom_27039;
	(*bottom_27039).Link[(1)- 0] = bottom_27039;
}

N_NOINLINE(void, setStackBottom)(void* thestackbottom) {
	{
		if (!(gch_46844.Stackbottom == NIM_NIL)) goto LA3;
		gch_46844.Stackbottom = thestackbottom;
	}
	goto LA1;
	LA3: ;
	{
		NI a;
		NI b;
		a = ((NI) (thestackbottom));
		b = ((NI) (gch_46844.Stackbottom));
		gch_46844.Stackbottom = ((void*) (((a >= b) ? a : b)));
	}
	LA1: ;
}

static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) ((&locals)));
	setStackBottom(locals);
}

static N_INLINE(NI, roundup_26270)(NI x, NI v) {
	NI result;
	result = 0;
	result = (NI)((NI32)(x + (NI32)(v - 1)) & (NI)((NU32) ~((NI32)(v - 1))));
	return result;
}

static N_INLINE(void, listremove_30603)(tbigchunk26242** head_30609, tbigchunk26242* c_30612) {
	{
		if (!(c_30612 == (*head_30609))) goto LA3;
		(*head_30609) = (*c_30612).Next;
		{
			if (!!(((*head_30609) == NIM_NIL))) goto LA7;
			(*(*head_30609)).Prev = NIM_NIL;
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		(*(*c_30612).Prev).Next = (*c_30612).Next;
		{
			if (!!(((*c_30612).Next == NIM_NIL))) goto LA12;
			(*(*c_30612).Next).Prev = (*c_30612).Prev;
		}
		LA12: ;
	}
	LA1: ;
	(*c_30612).Next = NIM_NIL;
	(*c_30612).Prev = NIM_NIL;
}

N_NIMCALL(ttrunk26213*, intsetget_28524)(tintset26217* t, NI key) {
	ttrunk26213* result;
	ttrunk26213* it;
	result = 0;
	it = (*t).Data[((NI)(key & 255))- 0];
	{
		while (1) {
			if (!!((it == NIM_NIL))) goto LA2;
			{
				if (!((*it).Key == key)) goto LA5;
				result = it;
				goto BeforeRet;
			}
			LA5: ;
			it = (*it).Next;
		} LA2: ;
	}
	result = NIM_NIL;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, contains_28595)(tintset26217* s, NI key) {
	NIM_BOOL result;
	ttrunk26213* t;
	result = 0;
	t = intsetget_28524(s, (NI)((NU32)(key) >> (NU32)(9)));
	{
		NI u;
		if (!!((t == NIM_NIL))) goto LA3;
		u = (NI)(key & 511);
		result = !(((NI)((*t).Bits[((NI)((NU32)(((NI) (u))) >> (NU32)(5)))- 0] & (NI)((NU32)(1) << (NU32)(((NI) ((NI)(((NI) (u)) & 31)))))) == 0));
	}
	goto LA1;
	LA3: ;
	{
		result = NIM_FALSE;
	}
	LA1: ;
	return result;
}

static N_INLINE(NI, pageindex_28938)(void* p) {
	NI result;
	result = 0;
	result = (NI)((NU32)(((NI) (p))) >> (NU32)(12));
	return result;
}

static N_INLINE(NIM_BOOL, isaccessible_29621)(tmemregion27010* a, void* p) {
	NIM_BOOL result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = pageindex_28938(p);
	result = contains_28595((&(*a).Chunkstarts), LOC1);
	return result;
}

static N_INLINE(void, updateprevsize_29691)(tmemregion27010* a, tbigchunk26242* c, NI prevsize) {
	tbasechunk26238* ri;
	ri = ((tbasechunk26238*) ((NI)((NU32)(((NI) (c))) + (NU32)((*c).Sup.Size))));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = isaccessible_29621((&(*a)), ((void*) (ri)));
		if (!LOC3) goto LA4;
		(*ri).Prevsize = prevsize;
	}
	LA4: ;
}

N_NOINLINE(void, raiseoutofmem_25659)(void) {
	{
		if (!!((outofmemhook_8233 == NIM_NIL))) goto LA3;
		outofmemhook_8233();
	}
	LA3: ;
	printf("%s\015\012", (((NimStringDesc*) &TMP2))->data);
	exit(1);
}

static N_INLINE(void*, osallocpages_26023)(NI size) {
	void* result;
	result = 0;
	result = VirtualAlloc(NIM_NIL, size, ((NI32) 12288), ((NI32) 4));
	{
		if (!(result == NIM_NIL)) goto LA3;
		raiseoutofmem_25659();
	}
	LA3: ;
	return result;
}

static N_INLINE(void, inccurrmem_27205)(tmemregion27010* a, NI bytes) {
	(*a).Currmem += bytes;
}

N_NIMCALL(void*, llalloc_27259)(tmemregion27010* a, NI size) {
	void* result;
	result = 0;
	{
		NIM_BOOL LOC3;
		tllchunk27004* old;
		void* LOC7;
		LOC3 = 0;
		LOC3 = ((*a).Llmem == NIM_NIL);
		if (LOC3) goto LA4;
		LOC3 = ((*(*a).Llmem).Size < size);
		LA4: ;
		if (!LOC3) goto LA5;
		old = (*a).Llmem;
		LOC7 = 0;
		LOC7 = osallocpages_26023(4096);
		(*a).Llmem = ((tllchunk27004*) (LOC7));
		inccurrmem_27205(a, 4096);
		(*(*a).Llmem).Size = (NI32)(4096 - ((NI)sizeof(tllchunk27004)));
		(*(*a).Llmem).Acc = ((NI)sizeof(tllchunk27004));
		(*(*a).Llmem).Next = old;
	}
	LA5: ;
	result = ((void*) ((NI32)(((NI) ((*a).Llmem)) + (*(*a).Llmem).Acc)));
	(*(*a).Llmem).Size -= size;
	(*(*a).Llmem).Acc += size;
	zeroMem(result, size);
	return result;
}

N_NIMCALL(ttrunk26213*, intsetput_28560)(tmemregion27010* a, tintset26217* t, NI key) {
	ttrunk26213* result;
	result = 0;
	result = intsetget_28524((&(*t)), key);
	{
		void* LOC5;
		if (!(result == NIM_NIL)) goto LA3;
		LOC5 = 0;
		LOC5 = llalloc_27259(a, ((NI)sizeof(ttrunk26213)));
		result = ((ttrunk26213*) (LOC5));
		(*result).Next = (*t).Data[((NI)(key & 255))- 0];
		(*t).Data[((NI)(key & 255))- 0] = result;
		(*result).Key = key;
	}
	LA3: ;
	return result;
}

N_NIMCALL(void, incl_28624)(tmemregion27010* a, tintset26217* s, NI key) {
	ttrunk26213* t;
	NI u;
	t = intsetput_28560(a, s, (NI)((NU32)(key) >> (NU32)(9)));
	u = (NI)(key & 511);
	(*t).Bits[((NI)((NU32)(((NI) (u))) >> (NU32)(5)))- 0] = (NI)((*t).Bits[((NI)((NU32)(((NI) (u))) >> (NU32)(5)))- 0] | (NI)((NU32)(1) << (NU32)(((NI) ((NI)(((NI) (u)) & 31))))));
}

static N_INLINE(NI, pageindex_28930)(tbasechunk26238* c) {
	NI result;
	result = 0;
	result = (NI)((NU32)(((NI) (c))) >> (NU32)(12));
	return result;
}

static N_INLINE(void, listadd_31831)(tbigchunk26242** head_31837, tbigchunk26242* c_31840) {
	(*c_31840).Next = (*head_31837);
	{
		if (!!(((*head_31837) == NIM_NIL))) goto LA3;
		(*(*head_31837)).Prev = c_31840;
	}
	LA3: ;
	(*head_31837) = c_31840;
}

N_NIMCALL(void, splitchunk_32615)(tmemregion27010* a, tbigchunk26242* c, NI size) {
	tbigchunk26242* rest;
	tbasechunk26238* LOC1;
	NI LOC2;
	rest = ((tbigchunk26242*) ((NI)((NU32)(((NI) (c))) + (NU32)(size))));
	(*rest).Sup.Size = (NI32)((*c).Sup.Size - size);
	(*rest).Sup.Used = NIM_FALSE;
	(*rest).Next = NIM_NIL;
	(*rest).Prev = NIM_NIL;
	(*rest).Sup.Prevsize = size;
	updateprevsize_29691(a, c, (*rest).Sup.Size);
	(*c).Sup.Size = size;
	LOC1 = 0;
	LOC1 = &rest->Sup;
	LOC2 = 0;
	LOC2 = pageindex_28930(LOC1);
	incl_28624(a, (&(*a).Chunkstarts), LOC2);
	listadd_31831((&(*a).Freechunkslist), rest);
}

N_NIMCALL(tbigchunk26242*, requestoschunks_28956)(tmemregion27010* a, NI size) {
	tbigchunk26242* result;
	void* LOC1;
	NI nxt;
	tbasechunk26238* next;
	NI lastsize;
	NI prv;
	tbasechunk26238* prev;
	result = 0;
	inccurrmem_27205(a, size);
	(*a).Freemem += size;
	LOC1 = 0;
	LOC1 = osallocpages_26023(size);
	result = ((tbigchunk26242*) (LOC1));
	(*result).Next = NIM_NIL;
	(*result).Prev = NIM_NIL;
	(*result).Sup.Used = NIM_FALSE;
	(*result).Sup.Size = size;
	nxt = (NI)((NU32)(((NI) (result))) + (NU32)(size));
	next = ((tbasechunk26238*) (nxt));
	{
		NI LOC4;
		NIM_BOOL LOC5;
		LOC4 = 0;
		LOC4 = pageindex_28930(next);
		LOC5 = 0;
		LOC5 = contains_28595((&(*a).Chunkstarts), LOC4);
		if (!LOC5) goto LA6;
		(*next).Prevsize = size;
	}
	LA6: ;
	{
		if (!!(((*a).Lastsize == 0))) goto LA10;
		lastsize = (*a).Lastsize;
	}
	goto LA8;
	LA10: ;
	{
		lastsize = 4096;
	}
	LA8: ;
	prv = (NI)((NU32)(((NI) (result))) - (NU32)(lastsize));
	prev = ((tbasechunk26238*) (prv));
	{
		NIM_BOOL LOC15;
		NI LOC16;
		LOC15 = 0;
		LOC16 = 0;
		LOC16 = pageindex_28930(prev);
		LOC15 = contains_28595((&(*a).Chunkstarts), LOC16);
		if (!(LOC15)) goto LA17;
		LOC15 = ((*prev).Size == lastsize);
		LA17: ;
		if (!LOC15) goto LA18;
		(*result).Sup.Prevsize = lastsize;
	}
	goto LA13;
	LA18: ;
	{
		(*result).Sup.Prevsize = 0;
	}
	LA13: ;
	(*a).Lastsize = size;
	return result;
}

N_NIMCALL(tbigchunk26242*, getbigchunk_32820)(tmemregion27010* a, NI size) {
	tbigchunk26242* result;
	tbasechunk26238* LOC16;
	NI LOC17;
	result = 0;
	result = (*a).Freechunkslist;
	{
		{
			while (1) {
				if (!!((result == NIM_NIL))) goto LA3;
				{
					if (!((*result).Sup.Size == size)) goto LA6;
					listremove_30603((&(*a).Freechunkslist), result);
					goto LA1;
				}
				goto LA4;
				LA6: ;
				{
					if (!(size < (*result).Sup.Size)) goto LA9;
					listremove_30603((&(*a).Freechunkslist), result);
					splitchunk_32615(a, result, size);
					goto LA1;
				}
				goto LA4;
				LA9: ;
				LA4: ;
				result = (*result).Next;
			} LA3: ;
		}
		{
			if (!(size < 524288)) goto LA13;
			result = requestoschunks_28956(a, 524288);
			splitchunk_32615(a, result, size);
		}
		goto LA11;
		LA13: ;
		{
			result = requestoschunks_28956(a, size);
		}
		LA11: ;
	} LA1: ;
	(*result).Sup.Prevsize = 0;
	(*result).Sup.Used = NIM_TRUE;
	LOC16 = 0;
	LOC16 = &result->Sup;
	LOC17 = 0;
	LOC17 = pageindex_28930(LOC16);
	incl_28624(a, (&(*a).Chunkstarts), LOC17);
	(*a).Freemem -= size;
	return result;
}

N_NIMCALL(tsmallchunk26240*, getsmallchunk_33628)(tmemregion27010* a) {
	tsmallchunk26240* result;
	tbigchunk26242* res;
	result = 0;
	res = getbigchunk_32820(a, 4096);
	result = ((tsmallchunk26240*) (res));
	return result;
}

static N_INLINE(void, listadd_35005)(tsmallchunk26240** head_35011, tsmallchunk26240* c_35014) {
	(*c_35014).Next = (*head_35011);
	{
		if (!!(((*head_35011) == NIM_NIL))) goto LA3;
		(*(*head_35011)).Prev = c_35014;
	}
	LA3: ;
	(*head_35011) = c_35014;
}

static N_INLINE(void, listremove_37803)(tsmallchunk26240** head_37809, tsmallchunk26240* c_37812) {
	{
		if (!(c_37812 == (*head_37809))) goto LA3;
		(*head_37809) = (*c_37812).Next;
		{
			if (!!(((*head_37809) == NIM_NIL))) goto LA7;
			(*(*head_37809)).Prev = NIM_NIL;
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		(*(*c_37812).Prev).Next = (*c_37812).Next;
		{
			if (!!(((*c_37812).Next == NIM_NIL))) goto LA12;
			(*(*c_37812).Next).Prev = (*c_37812).Prev;
		}
		LA12: ;
	}
	LA1: ;
	(*c_37812).Next = NIM_NIL;
	(*c_37812).Prev = NIM_NIL;
}

N_NIMCALL(tavlnode27008*, allocavlnode_27436)(tmemregion27010* a, NI key, NI upperbound) {
	tavlnode27008* result;
	result = 0;
	{
		if (!!(((*a).Freeavlnodes == NIM_NIL))) goto LA3;
		result = (*a).Freeavlnodes;
		(*a).Freeavlnodes = (*(*a).Freeavlnodes).Link[(0)- 0];
	}
	goto LA1;
	LA3: ;
	{
		void* LOC6;
		LOC6 = 0;
		LOC6 = llalloc_27259(a, ((NI)sizeof(tavlnode27008)));
		result = ((tavlnode27008*) (LOC6));
	}
	LA1: ;
	(*result).Key = key;
	(*result).Upperbound = upperbound;
	(*result).Link[(0)- 0] = bottom_27039;
	(*result).Link[(1)- 0] = bottom_27039;
	(*result).Level = 1;
	return result;
}

N_NIMCALL(void, skew_28196)(tavlnode27008** t) {
	{
		tavlnode27008* temp;
		if (!((*(*(*t)).Link[(0)- 0]).Level == (*(*t)).Level)) goto LA3;
		temp = (*t);
		(*t) = (*(*t)).Link[(0)- 0];
		(*temp).Link[(0)- 0] = (*(*t)).Link[(1)- 0];
		(*(*t)).Link[(1)- 0] = temp;
	}
	LA3: ;
}

N_NIMCALL(void, split_28204)(tavlnode27008** t) {
	{
		tavlnode27008* temp;
		if (!((*(*(*(*t)).Link[(1)- 0]).Link[(1)- 0]).Level == (*(*t)).Level)) goto LA3;
		temp = (*t);
		(*t) = (*(*t)).Link[(1)- 0];
		(*temp).Link[(1)- 0] = (*(*t)).Link[(0)- 0];
		(*(*t)).Link[(0)- 0] = temp;
		(*(*t)).Level += 1;
	}
	LA3: ;
}

N_NIMCALL(void, add_28224)(tmemregion27010* a, tavlnode27008** t, NI key, NI upperbound) {
	{
		if (!((*t) == bottom_27039)) goto LA3;
		(*t) = allocavlnode_27436(a, key, upperbound);
	}
	goto LA1;
	LA3: ;
	{
		{
			if (!((NU32)(key) < (NU32)((*(*t)).Key))) goto LA8;
			add_28224(a, &(*(*t)).Link[(0)- 0], key, upperbound);
		}
		goto LA6;
		LA8: ;
		{
			if (!((NU32)((*(*t)).Key) < (NU32)(key))) goto LA11;
			add_28224(a, &(*(*t)).Link[(1)- 0], key, upperbound);
		}
		goto LA6;
		LA11: ;
		{
		}
		LA6: ;
		skew_28196(t);
		split_28204(t);
	}
	LA1: ;
}

N_NIMCALL(void*, rawalloc_34146)(tmemregion27010* a, NI requestedsize) {
	void* result;
	NI size;
	result = 0;
	size = roundup_26270(requestedsize, 8);
	{
		NI s;
		tsmallchunk26240* c;
		if (!(size <= (NI32)(4096 - (NI32)(((NI)sizeof(tsmallchunk26240)) - 8)))) goto LA3;
		s = (NI32)(size / 8);
		c = (*a).Freesmallchunks[(s)- 0];
		{
			if (!(c == NIM_NIL)) goto LA7;
			c = getsmallchunk_33628(a);
			(*c).Freelist = NIM_NIL;
			(*c).Sup.Size = size;
			(*c).Acc = size;
			(*c).Free = (NI32)((NI32)(4096 - (NI32)(((NI)sizeof(tsmallchunk26240)) - 8)) - size);
			(*c).Next = NIM_NIL;
			(*c).Prev = NIM_NIL;
			listadd_35005((&(*a).Freesmallchunks[(s)- 0]), c);
			result = ((void*) ((&(*c).Data)));
		}
		goto LA5;
		LA7: ;
		{
			{
				if (!((*c).Freelist == NIM_NIL)) goto LA12;
				result = ((void*) ((NI)((NU32)(((NI) ((&(*c).Data)))) + (NU32)((*c).Acc))));
				(*c).Acc += size;
			}
			goto LA10;
			LA12: ;
			{
				result = ((void*) ((*c).Freelist));
				(*c).Freelist = (*(*c).Freelist).Next;
			}
			LA10: ;
			(*c).Free -= size;
		}
		LA5: ;
		{
			if (!((*c).Free < size)) goto LA17;
			listremove_37803((&(*a).Freesmallchunks[(s)- 0]), c);
		}
		LA17: ;
	}
	goto LA1;
	LA3: ;
	{
		tbigchunk26242* c;
		size = roundup_26270((NI32)(requestedsize + (NI32)(((NI)sizeof(tbigchunk26242)) - 8)), 4096);
		c = getbigchunk_32820(a, size);
		result = ((void*) ((&(*c).Data)));
		{
			if (!((*a).Root == NIM_NIL)) goto LA22;
			(*a).Root = bottom_27039;
		}
		LA22: ;
		add_28224(a, &(*a).Root, ((NI) (result)), (NI)((NU32)(((NI) (result))) + (NU32)(size)));
	}
	LA1: ;
	return result;
}

N_NIMCALL(void*, alloc_43234)(tmemregion27010* allocator, NI size) {
	void* result;
	result = 0;
	result = rawalloc_34146(allocator, (NI32)(size + ((NI)sizeof(tfreecell26230))));
	(*((tfreecell26230*) (result))).Zerofield = 1;
	result = ((void*) ((NI)((NU32)(((NI) (result))) + (NU32)(((NI)sizeof(tfreecell26230))))));
	return result;
}

N_NIMCALL(void*, alloc0_43419)(tmemregion27010* allocator, NI size) {
	void* result;
	result = 0;
	result = alloc_43234(allocator, size);
	zeroMem(result, size);
	return result;
}

N_NOCONV(void*, alloc0_5817)(NI size) {
	void* result;
	result = 0;
	result = alloc0_43419((&gch_46844.Region), size);
	return result;
}

N_NIMCALL(void, init_44847)(tcellseq44749* s, NI cap) {
	void* LOC1;
	(*s).Len = 0;
	(*s).Cap = cap;
	LOC1 = 0;
	LOC1 = alloc0_5817((NI32)(cap * 4));
	(*s).D = ((tcell44733**) (LOC1));
}

N_NIMCALL(void, init_44868)(tcellset44745* s) {
	void* LOC1;
	LOC1 = 0;
	LOC1 = alloc0_5817(4096);
	(*s).Data = ((tpagedesc44741**) (LOC1));
	(*s).Max = 1023;
	(*s).Counter = 0;
	(*s).Head = NIM_NIL;
}

N_NIMCALL(void, initgc_9201)(void) {
	gch_46844.Cyclethreshold = 4194304;
	gch_46844.Stat.Stackscans = 0;
	gch_46844.Stat.Cyclecollections = 0;
	gch_46844.Stat.Maxthreshold = 0;
	gch_46844.Stat.Maxstacksize = 0;
	gch_46844.Stat.Maxstackcells = 0;
	gch_46844.Stat.Cycletablesize = 0;
	init_44847((&gch_46844.Zct), 1024);
	init_44847((&gch_46844.Tempstack), 1024);
	init_44868((&gch_46844.Cycleroots));
	init_44847((&gch_46844.Decstack), 1024);
}

static N_INLINE(NI, getoccupiedmem_44668)(tmemregion27010* a) {
	NI result;
	result = 0;
	result = (NI32)((*a).Currmem - (*a).Freemem);
	return result;
}

N_NOINLINE(NI, stacksize_68810)(void) {
	NI result;
	void* volatile stacktop;
	result = 0;
	stacktop = 0;
	result = ((NI32)(((NI) ((&stacktop))) - ((NI) (gch_46844.Stackbottom))) > 0? ((NI32)(((NI) ((&stacktop))) - ((NI) (gch_46844.Stackbottom)))) : -((NI32)(((NI) ((&stacktop))) - ((NI) (gch_46844.Stackbottom)))));
	return result;
}

N_NIMCALL(NI, lowgauge_28018)(tavlnode27008* n) {
	NI result;
	tavlnode27008* it;
	result = 0;
	it = n;
	{
		while (1) {
			if (!!((it == bottom_27039))) goto LA2;
			result = (*it).Key;
			it = (*it).Link[(0)- 0];
		} LA2: ;
	}
	return result;
}

N_NIMCALL(NI, highgauge_28049)(tavlnode27008* n) {
	NI result;
	tavlnode27008* it;
	result = 0;
	result = -1;
	it = n;
	{
		while (1) {
			if (!!((it == bottom_27039))) goto LA2;
			result = (*it).Upperbound;
			it = (*it).Link[(1)- 0];
		} LA2: ;
	}
	return result;
}

static N_INLINE(void, prepareforinteriorpointerchecking_42082)(tmemregion27010* a) {
	(*a).Minlargeobj = lowgauge_28018((*a).Root);
	(*a).Maxlargeobj = highgauge_28049((*a).Root);
}

static N_INLINE(tcell44733*, usrtocell_48446)(void* usr) {
	tcell44733* result;
	result = 0;
	result = ((tcell44733*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell44733))))));
	return result;
}

static N_INLINE(tbasechunk26238*, pageaddr_28946)(void* p) {
	tbasechunk26238* result;
	result = 0;
	result = ((tbasechunk26238*) ((NI)(((NI) (p)) & -4096)));
	return result;
}

static N_INLINE(NIM_BOOL, chunkunused_28810)(tbasechunk26238* c) {
	NIM_BOOL result;
	result = 0;
	result = !((*c).Used);
	return result;
}

static N_INLINE(NIM_BOOL, issmallchunk_28799)(tbasechunk26238* c) {
	NIM_BOOL result;
	result = 0;
	result = ((*c).Size <= (NI32)(4096 - (NI32)(((NI)sizeof(tsmallchunk26240)) - 8)));
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(tavlnode27008*, inrange_28129)(tavlnode27008* root, NI key) {
	tavlnode27008* result;
	tavlnode27008* it;
	result = 0;
	it = root;
	{
		while (1) {
			if (!!((it == bottom_27039))) goto LA2;
			{
				NIM_BOOL LOC5;
				LOC5 = 0;
				LOC5 = ((NU32)((*it).Key) <= (NU32)(key));
				if (!(LOC5)) goto LA6;
				LOC5 = ((NU32)(key) < (NU32)((*it).Upperbound));
				LA6: ;
				if (!LOC5) goto LA7;
				result = it;
				goto BeforeRet;
			}
			LA7: ;
			it = (*it).Link[(((NU32)((*it).Key) < (NU32)(key)))- 0];
		} LA2: ;
	}
	BeforeRet: ;
	return result;
}

N_NIMCALL(void*, interiorallocatedptr_42089)(tmemregion27010* a, void* p) {
	void* result;
	result = 0;
	{
		NIM_BOOL LOC3;
		tbasechunk26238* c_42094;
		LOC3 = 0;
		LOC3 = isaccessible_29621(a, p);
		if (!LOC3) goto LA4;
		c_42094 = pageaddr_28946(p);
		{
			NIM_BOOL LOC8;
			LOC8 = 0;
			LOC8 = chunkunused_28810(c_42094);
			if (!!(LOC8)) goto LA9;
			{
				NIM_BOOL LOC13;
				tsmallchunk26240* c;
				NI offset;
				LOC13 = 0;
				LOC13 = issmallchunk_28799(c_42094);
				if (!LOC13) goto LA14;
				c = ((tsmallchunk26240*) (c_42094));
				offset = (NI)((NU32)((NI)(((NI) (p)) & 4095)) - (NU32)((NI32)(((NI)sizeof(tsmallchunk26240)) - 8)));
				{
					tfreecell26230* d;
					if (!((NU32)(offset) < (NU32)((*c).Acc))) goto LA18;
					d = ((tfreecell26230*) ((NI)((NU32)((NI)((NU32)(((NI) ((&(*c).Data)))) + (NU32)(offset))) - (NU32)((NI)((NU32)(offset) % (NU32)((*c).Sup.Size))))));
					{
						if (!((NU32)(1) < (NU32)((*d).Zerofield))) goto LA22;
						result = ((void*) (d));
					}
					LA22: ;
				}
				LA18: ;
			}
			goto LA11;
			LA14: ;
			{
				tbigchunk26242* c;
				NF* d;
				c = ((tbigchunk26242*) (c_42094));
				d = (&(*c).Data);
				{
					NIM_BOOL LOC27;
					LOC27 = 0;
					LOC27 = (((void*) (d)) <= p);
					if (!(LOC27)) goto LA28;
					LOC27 = ((NU32)(1) < (NU32)((*((tfreecell26230*) (d))).Zerofield));
					LA28: ;
					if (!LOC27) goto LA29;
					result = ((void*) (d));
				}
				LA29: ;
			}
			LA11: ;
		}
		LA9: ;
	}
	goto LA1;
	LA4: ;
	{
		NI q;
		q = ((NI) (p));
		{
			NIM_BOOL LOC34;
			tavlnode27008* avlnode;
			LOC34 = 0;
			LOC34 = ((NU32)((*a).Minlargeobj) <= (NU32)(q));
			if (!(LOC34)) goto LA35;
			LOC34 = ((NU32)(q) <= (NU32)((*a).Maxlargeobj));
			LA35: ;
			if (!LOC34) goto LA36;
			avlnode = inrange_28129((*a).Root, q);
			{
				void* k;
				tbigchunk26242* c;
				tbasechunk26238* LOC42;
				if (!!((avlnode == NIM_NIL))) goto LA40;
				k = ((void*) ((*avlnode).Key));
				LOC42 = 0;
				LOC42 = pageaddr_28946(k);
				c = ((tbigchunk26242*) (LOC42));
				{
					if (!((NU32)(1) < (NU32)((*((tfreecell26230*) (k))).Zerofield))) goto LA45;
					result = k;
				}
				LA45: ;
			}
			LA40: ;
		}
		LA36: ;
	}
	LA1: ;
	return result;
}

N_NOCONV(void*, alloc_5801)(NI size) {
	void* result;
	result = 0;
	result = alloc_43234((&gch_46844.Region), size);
	return result;
}

N_NIMCALL(void, excl_28638)(tintset26217* s, NI key) {
	ttrunk26213* t;
	t = intsetget_28524((&(*s)), (NI)((NU32)(key) >> (NU32)(9)));
	{
		NI u;
		if (!!((t == NIM_NIL))) goto LA3;
		u = (NI)(key & 511);
		(*t).Bits[((NI)((NU32)(((NI) (u))) >> (NU32)(5)))- 0] = (NI)((*t).Bits[((NI)((NU32)(((NI) (u))) >> (NU32)(5)))- 0] & (NI)((NU32) ~((NI)((NU32)(1) << (NU32)(((NI) ((NI)(((NI) (u)) & 31))))))));
	}
	LA3: ;
}

static N_INLINE(void, osdeallocpages_26031)(void* p, NI size) {
	VirtualFree(p, 0, ((NI32) 32768));
}

static N_INLINE(void, deccurrmem_27225)(tmemregion27010* a, NI bytes) {
	(*a).Maxmem = (((*a).Maxmem >= (*a).Currmem) ? (*a).Maxmem : (*a).Currmem);
	(*a).Currmem -= bytes;
}

N_NIMCALL(void, freeoschunks_29410)(tmemregion27010* a, void* p, NI size) {
	tbasechunk26238* c;
	NI nxt;
	tbasechunk26238* next;
	NI LOC7;
	c = ((tbasechunk26238*) (p));
	nxt = (NI)((NU32)(((NI) (p))) + (NU32)((*c).Size));
	next = ((tbasechunk26238*) (nxt));
	{
		NI LOC3;
		NIM_BOOL LOC4;
		LOC3 = 0;
		LOC3 = pageindex_28930(next);
		LOC4 = 0;
		LOC4 = contains_28595((&(*a).Chunkstarts), LOC3);
		if (!LOC4) goto LA5;
		(*next).Prevsize = 0;
	}
	LA5: ;
	LOC7 = 0;
	LOC7 = pageindex_28938(p);
	excl_28638((&(*a).Chunkstarts), LOC7);
	osdeallocpages_26031(p, size);
	deccurrmem_27225(a, size);
	(*a).Freemem -= size;
}

N_NIMCALL(void, freebigchunk_29806)(tmemregion27010* a, tbigchunk26242* c_29810) {
	tbigchunk26242* c;
	tbasechunk26238* ri;
	c = c_29810;
	(*a).Freemem += (*c).Sup.Size;
	ri = ((tbasechunk26238*) ((NI)((NU32)(((NI) (c))) + (NU32)((*c).Sup.Size))));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = isaccessible_29621((&(*a)), ((void*) (ri)));
		if (!(LOC3)) goto LA4;
		LOC3 = chunkunused_28810(ri);
		LA4: ;
		if (!LOC3) goto LA5;
		{
			NIM_BOOL LOC9;
			NI LOC12;
			LOC9 = 0;
			LOC9 = issmallchunk_28799(ri);
			if (!!(LOC9)) goto LA10;
			listremove_30603((&(*a).Freechunkslist), ((tbigchunk26242*) (ri)));
			(*c).Sup.Size += (*ri).Size;
			LOC12 = 0;
			LOC12 = pageindex_28930(ri);
			excl_28638((&(*a).Chunkstarts), LOC12);
		}
		LA10: ;
	}
	LA5: ;
	{
		tbasechunk26238* le;
		if (!!(((*c).Sup.Prevsize == 0))) goto LA15;
		le = ((tbasechunk26238*) ((NI)((NU32)(((NI) (c))) - (NU32)((*c).Sup.Prevsize))));
		{
			NIM_BOOL LOC19;
			LOC19 = 0;
			LOC19 = isaccessible_29621((&(*a)), ((void*) (le)));
			if (!(LOC19)) goto LA20;
			LOC19 = chunkunused_28810(le);
			LA20: ;
			if (!LOC19) goto LA21;
			{
				NIM_BOOL LOC25;
				tbasechunk26238* LOC28;
				NI LOC29;
				LOC25 = 0;
				LOC25 = issmallchunk_28799(le);
				if (!!(LOC25)) goto LA26;
				listremove_30603((&(*a).Freechunkslist), ((tbigchunk26242*) (le)));
				(*le).Size += (*c).Sup.Size;
				LOC28 = 0;
				LOC28 = &c->Sup;
				LOC29 = 0;
				LOC29 = pageindex_28930(LOC28);
				excl_28638((&(*a).Chunkstarts), LOC29);
				c = ((tbigchunk26242*) (le));
			}
			LA26: ;
		}
		LA21: ;
	}
	LA15: ;
	{
		NIM_BOOL LOC32;
		tbasechunk26238* LOC36;
		NI LOC37;
		LOC32 = 0;
		LOC32 = ((*c).Sup.Size < 1048576);
		if (LOC32) goto LA33;
		LOC32 = NIM_TRUE;
		LA33: ;
		if (!LOC32) goto LA34;
		LOC36 = 0;
		LOC36 = &c->Sup;
		LOC37 = 0;
		LOC37 = pageindex_28930(LOC36);
		incl_28624(a, (&(*a).Chunkstarts), LOC37);
		updateprevsize_29691(a, c, (*c).Sup.Size);
		listadd_31831((&(*a).Freechunkslist), c);
		(*c).Sup.Used = NIM_FALSE;
	}
	goto LA30;
	LA34: ;
	{
		freeoschunks_29410(a, ((void*) (c)), (*c).Sup.Size);
	}
	LA30: ;
}

static N_INLINE(void, deallocavlnode_28006)(tmemregion27010* a, tavlnode27008* n) {
	(*n).Link[(0)- 0] = (*a).Freeavlnodes;
	(*a).Freeavlnodes = n;
}

N_NIMCALL(void, del_28404)(tmemregion27010* a, tavlnode27008** t, NI x) {
	{
		if (!((*t) == bottom_27039)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	(*a).Last = (*t);
	{
		if (!((NU32)(x) < (NU32)((*(*t)).Key))) goto LA7;
		del_28404(a, &(*(*t)).Link[(0)- 0], x);
	}
	goto LA5;
	LA7: ;
	{
		(*a).Deleted = (*t);
		del_28404(a, &(*(*t)).Link[(1)- 0], x);
	}
	LA5: ;
	{
		NIM_BOOL LOC12;
		NIM_BOOL LOC13;
		LOC12 = 0;
		LOC13 = 0;
		LOC13 = ((*t) == (*a).Last);
		if (!(LOC13)) goto LA14;
		LOC13 = !(((*a).Deleted == bottom_27039));
		LA14: ;
		LOC12 = LOC13;
		if (!(LOC12)) goto LA15;
		LOC12 = (x == (*(*a).Deleted).Key);
		LA15: ;
		if (!LOC12) goto LA16;
		(*(*a).Deleted).Key = (*(*t)).Key;
		(*(*a).Deleted).Upperbound = (*(*t)).Upperbound;
		(*a).Deleted = bottom_27039;
		(*t) = (*(*t)).Link[(1)- 0];
		deallocavlnode_28006(a, (*a).Last);
	}
	goto LA10;
	LA16: ;
	{
		NIM_BOOL LOC19;
		LOC19 = 0;
		LOC19 = ((*(*(*t)).Link[(0)- 0]).Level < (NI32)((*(*t)).Level - 1));
		if (LOC19) goto LA20;
		LOC19 = ((*(*(*t)).Link[(1)- 0]).Level < (NI32)((*(*t)).Level - 1));
		LA20: ;
		if (!LOC19) goto LA21;
		(*(*t)).Level -= 1;
		{
			if (!((*(*t)).Level < (*(*(*t)).Link[(1)- 0]).Level)) goto LA25;
			(*(*(*t)).Link[(1)- 0]).Level = (*(*t)).Level;
		}
		LA25: ;
		skew_28196(t);
		skew_28196(&(*(*t)).Link[(1)- 0]);
		skew_28196(&(*(*(*t)).Link[(1)- 0]).Link[(1)- 0]);
		split_28204(t);
		split_28204(&(*(*t)).Link[(1)- 0]);
	}
	goto LA10;
	LA21: ;
	LA10: ;
	BeforeRet: ;
}

N_NIMCALL(void, rawdealloc_40423)(tmemregion27010* a, void* p) {
	tbasechunk26238* c_40601;
	c_40601 = pageaddr_28946(p);
	{
		NIM_BOOL LOC3;
		tsmallchunk26240* c;
		NI s;
		tfreecell26230* f;
		LOC3 = 0;
		LOC3 = issmallchunk_28799(c_40601);
		if (!LOC3) goto LA4;
		c = ((tsmallchunk26240*) (c_40601));
		s = (*c).Sup.Size;
		f = ((tfreecell26230*) (p));
		(*f).Zerofield = 0;
		(*f).Next = (*c).Freelist;
		(*c).Freelist = f;
		{
			if (!((*c).Free < s)) goto LA8;
			listadd_35005((&(*a).Freesmallchunks[((NI32)(s / 8))- 0]), c);
			(*c).Free += s;
		}
		goto LA6;
		LA8: ;
		{
			(*c).Free += s;
			{
				if (!((*c).Free == (NI32)(4096 - (NI32)(((NI)sizeof(tsmallchunk26240)) - 8)))) goto LA13;
				listremove_37803((&(*a).Freesmallchunks[((NI32)(s / 8))- 0]), c);
				(*c).Sup.Size = 4096;
				freebigchunk_29806(a, ((tbigchunk26242*) (c)));
			}
			LA13: ;
		}
		LA6: ;
	}
	goto LA1;
	LA4: ;
	{
		tbigchunk26242* c;
		c = ((tbigchunk26242*) (c_40601));
		(*a).Deleted = bottom_27039;
		del_28404(a, &(*a).Root, ((NI) ((&(*c).Data))));
		freebigchunk_29806(a, c);
	}
	LA1: ;
}

N_NIMCALL(void, dealloc_43428)(tmemregion27010* allocator, void* p) {
	void* x;
	x = ((void*) ((NI)((NU32)(((NI) (p))) - (NU32)(((NI)sizeof(tfreecell26230))))));
	rawdealloc_40423(allocator, x);
}

N_NOCONV(void, dealloc_5848)(void* p) {
	dealloc_43428((&gch_46844.Region), p);
}

static N_INLINE(void, add_44821)(tcellseq44749* s, tcell44733* c) {
	{
		tcell44733** d;
		void* LOC5;
		if (!((*s).Cap <= (*s).Len)) goto LA3;
		(*s).Cap = (NI32)((NI32)((*s).Cap * 3) / 2);
		LOC5 = 0;
		LOC5 = alloc_5801((NI32)((*s).Cap * 4));
		d = ((tcell44733**) (LOC5));
		memcpy(((void*) (d)), ((void*) ((*s).D)), (NI32)((*s).Len * 4));
		dealloc_5848(((void*) ((*s).D)));
		(*s).D = d;
	}
	LA3: ;
	(*s).D[((*s).Len)- 0] = c;
	(*s).Len += 1;
}

static N_INLINE(void, gcmark_67446)(tgcheap46816* gch, void* p) {
	tcell44733* cell;
	NI c;
	cell = usrtocell_48446(p);
	c = ((NI) (cell));
	{
		tcell44733* objstart;
		void* LOC5;
		if (!((NU32)(4096) < (NU32)(c))) goto LA3;
		LOC5 = 0;
		LOC5 = interiorallocatedptr_42089((&(*gch).Region), ((void*) (cell)));
		objstart = ((tcell44733*) (LOC5));
		{
			if (!!((objstart == NIM_NIL))) goto LA8;
			(*objstart).Refcount = (NI)((NU32)((*objstart).Refcount) + (NU32)(8));
			add_44821((&(*gch).Decstack), objstart);
		}
		LA8: ;
	}
	LA3: ;
}

N_CDECL(void, markstackandregisters_69040)(tgcheap46816* gch) {
	jmp_buf registers;
	{
		int LOC3;
		NI max;
		NI sp;
		LOC3 = 0;
		LOC3 = setjmp(registers);
		if (!(LOC3 == ((NI32) 0))) goto LA4;
		max = ((NI) ((*gch).Stackbottom));
		sp = ((NI) ((&registers)));
		{
			while (1) {
				if (!((NU32)(sp) < (NU32)((NI32)(max - 32)))) goto LA7;
				gcmark_67446(gch, ((void**) (sp))[(0)- 0]);
				gcmark_67446(gch, ((void**) (sp))[(1)- 0]);
				gcmark_67446(gch, ((void**) (sp))[(2)- 0]);
				gcmark_67446(gch, ((void**) (sp))[(3)- 0]);
				gcmark_67446(gch, ((void**) (sp))[(4)- 0]);
				gcmark_67446(gch, ((void**) (sp))[(5)- 0]);
				gcmark_67446(gch, ((void**) (sp))[(6)- 0]);
				gcmark_67446(gch, ((void**) (sp))[(7)- 0]);
				sp = (NI)((NU32)(sp) + (NU32)(32));
			} LA7: ;
		}
		{
			while (1) {
				if (!((NU32)(sp) <= (NU32)(max))) goto LA9;
				gcmark_67446(gch, (*((void**) (sp))));
				sp = (NI)((NU32)(sp) + (NU32)(4));
			} LA9: ;
		}
	}
	LA4: ;
}

N_NIMCALL(void, markthreadstacks_68006)(tgcheap46816* gch) {
}

static N_INLINE(NIM_BOOL, canbecycleroot_48467)(tcell44733* c) {
	NIM_BOOL result;
	result = 0;
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	return result;
}

static N_INLINE(NI, nexttry_44912)(NI h, NI maxhash) {
	NI result;
	result = 0;
	result = (NI)((NI32)((NI32)(5 * h) + 1) & maxhash);
	return result;
}

N_NIMCALL(tpagedesc44741*, cellsetget_44920)(tcellset44745 t, NI key) {
	tpagedesc44741* result;
	NI h;
	result = 0;
	h = (NI)(((NI) (key)) & t.Max);
	{
		while (1) {
			if (!!((t.Data[(h)- 0] == NIM_NIL))) goto LA2;
			{
				if (!((*t.Data[(h)- 0]).Key == key)) goto LA5;
				result = t.Data[(h)- 0];
				goto BeforeRet;
			}
			LA5: ;
			h = nexttry_44912(h, t.Max);
		} LA2: ;
	}
	result = NIM_NIL;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, excl_45502)(tcellset44745* s, tcell44733* cell) {
	NI u;
	tpagedesc44741* t;
	u = ((NI) (cell));
	t = cellsetget_44920((*s), (NI)((NU32)(u) >> (NU32)(12)));
	{
		if (!!((t == NIM_NIL))) goto LA3;
		u = (NI)((NU32)((NI)((NU32)(u) % (NU32)(4096))) / (NU32)(8));
		(*t).Bits[((NI)((NU32)(u) >> (NU32)(5)))- 0] = (NI)((*t).Bits[((NI)((NU32)(u) >> (NU32)(5)))- 0] & (NI)((NU32) ~((NI)((NU32)(1) << (NU32)(((NI) ((NI)(u & 31))))))));
	}
	LA3: ;
}

static N_INLINE(void*, celltousr_48425)(tcell44733* cell) {
	void* result;
	result = 0;
	result = ((void*) ((NI)((NU32)(((NI) (cell))) + (NU32)(((NI)sizeof(tcell44733))))));
	return result;
}

N_NIMCALL(void, preparedealloc_49008)(tcell44733* cell) {
	{
		void* LOC5;
		if (!!(((*(*cell).Typ).finalizer == NIM_NIL))) goto LA3;
		gch_46844.Recgclock += 1;
		LOC5 = 0;
		LOC5 = celltousr_48425(cell);
		((TFinalizer) ((*(*cell).Typ).finalizer))(LOC5);
		gch_46844.Recgclock -= 1;
	}
	LA3: ;
}

N_NOINLINE(void, addzct_48417)(tcellseq44749* s, tcell44733* c) {
	{
		if (!((NI)((*c).Refcount & 4) == 0)) goto LA3;
		(*c).Refcount = (NI)((*c).Refcount | 4);
		add_44821(s, c);
	}
	LA3: ;
}

static N_INLINE(void, rtladdzct_50004)(tcell44733* c) {
	addzct_48417((&gch_46844.Zct), c);
}

N_NIMCALL(void, cellsetrawinsert_44954)(tcellset44745 t, tpagedesc44741** data, tpagedesc44741* desc) {
	NI h;
	h = (NI)(((NI) ((*desc).Key)) & t.Max);
	{
		while (1) {
			if (!!((data[(h)- 0] == NIM_NIL))) goto LA2;
			h = nexttry_44912(h, t.Max);
		} LA2: ;
	}
	data[(h)- 0] = desc;
}

N_NIMCALL(void, cellsetenlarge_45212)(tcellset44745* t) {
	NI oldmax;
	tpagedesc44741** n;
	void* LOC1;
	oldmax = (*t).Max;
	(*t).Max = (NI32)((NI32)((NI32)((*t).Max + 1) * 2) - 1);
	LOC1 = 0;
	LOC1 = alloc0_5817((NI32)((NI32)((*t).Max + 1) * 4));
	n = ((tpagedesc44741**) (LOC1));
	{
		NI i_45229;
		NI res_45252;
		i_45229 = 0;
		res_45252 = 0;
		{
			while (1) {
				if (!(res_45252 <= oldmax)) goto LA4;
				i_45229 = res_45252;
				{
					if (!!(((*t).Data[(i_45229)- 0] == NIM_NIL))) goto LA7;
					cellsetrawinsert_44954((*t), n, (*t).Data[(i_45229)- 0]);
				}
				LA7: ;
				res_45252 += 1;
			} LA4: ;
		}
	}
	dealloc_5848(((void*) ((*t).Data)));
	(*t).Data = n;
}

N_NIMCALL(tpagedesc44741*, cellsetput_45266)(tcellset44745* t, NI key) {
	tpagedesc44741* result;
	NI h;
	void* LOC19;
	result = 0;
	h = (NI)(((NI) (key)) & (*t).Max);
	{
		while (1) {
			tpagedesc44741* x;
			x = (*t).Data[(h)- 0];
			{
				if (!(x == NIM_NIL)) goto LA5;
				goto LA1;
			}
			LA5: ;
			{
				if (!((*x).Key == key)) goto LA9;
				result = x;
				goto BeforeRet;
			}
			LA9: ;
			h = nexttry_44912(h, (*t).Max);
		}
	} LA1: ;
	{
		NIM_BOOL LOC13;
		LOC13 = 0;
		LOC13 = ((NI32)((NI32)((*t).Max + 1) * 2) < (NI32)((*t).Counter * 3));
		if (LOC13) goto LA14;
		LOC13 = ((NI32)((NI32)((*t).Max + 1) - (*t).Counter) < 4);
		LA14: ;
		if (!LOC13) goto LA15;
		cellsetenlarge_45212(t);
	}
	LA15: ;
	(*t).Counter += 1;
	h = (NI)(((NI) (key)) & (*t).Max);
	{
		while (1) {
			if (!!(((*t).Data[(h)- 0] == NIM_NIL))) goto LA18;
			h = nexttry_44912(h, (*t).Max);
		} LA18: ;
	}
	LOC19 = 0;
	LOC19 = alloc0_5817(((NI)sizeof(tpagedesc44741)));
	result = ((tpagedesc44741*) (LOC19));
	(*result).Next = (*t).Head;
	(*result).Key = key;
	(*t).Head = result;
	(*t).Data[(h)- 0] = result;
	BeforeRet: ;
	return result;
}

N_NOINLINE(void, incl_45471)(tcellset44745* s, tcell44733* cell) {
	NI u;
	tpagedesc44741* t;
	u = ((NI) (cell));
	t = cellsetput_45266(s, (NI)((NU32)(u) >> (NU32)(12)));
	u = (NI)((NU32)((NI)((NU32)(u) % (NU32)(4096))) / (NU32)(8));
	(*t).Bits[((NI)((NU32)(u) >> (NU32)(5)))- 0] = (NI)((*t).Bits[((NI)((NU32)(u) >> (NU32)(5)))- 0] | (NI)((NU32)(1) << (NU32)(((NI) ((NI)(u & 31))))));
}

static N_INLINE(void, rtladdcycleroot_49229)(tcell44733* c) {
	{
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		incl_45471((&gch_46844.Cycleroots), c);
	}
	LA3: ;
}

static N_INLINE(void, decref_50404)(tcell44733* c) {
	{
		(*c).Refcount -= 8;
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		rtladdzct_50004(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		LOC6 = 0;
		LOC6 = canbecycleroot_48467(c);
		if (!LOC6) goto LA7;
		rtladdcycleroot_49229(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
}

N_NIMCALL(void, markgray_64005)(tcell44733* s) {
	{
		if (!!((((NI) ((NI)((*s).Refcount & 3))) == 1))) goto LA3;
		(*s).Refcount = (NI)((NI)((*s).Refcount & -4) | 1);
		forallchildren_48817(s, ((NU8) 5));
	}
	LA3: ;
}

N_NIMCALL(void, scanblack_64204)(tcell44733* s) {
	(*s).Refcount = (NI)((*s).Refcount & -4);
	forallchildren_48817(s, ((NU8) 7));
}

N_NIMCALL(void, scan_64404)(tcell44733* s) {
	{
		if (!(((NI) ((NI)((*s).Refcount & 3))) == 1)) goto LA3;
		{
			if (!((NU32)(8) <= (NU32)((*s).Refcount))) goto LA7;
			scanblack_64204(s);
		}
		goto LA5;
		LA7: ;
		{
			(*s).Refcount = (NI)((NI)((*s).Refcount & -4) | 2);
			forallchildren_48817(s, ((NU8) 6));
		}
		LA5: ;
	}
	LA3: ;
}

N_NIMCALL(NIM_BOOL, contains_45423)(tcellset44745 s, tcell44733* cell) {
	NIM_BOOL result;
	NI u;
	tpagedesc44741* t;
	result = 0;
	u = ((NI) (cell));
	t = cellsetget_44920(s, (NI)((NU32)(u) >> (NU32)(12)));
	{
		if (!!((t == NIM_NIL))) goto LA3;
		u = (NI)((NU32)((NI)((NU32)(u) % (NU32)(4096))) / (NU32)(8));
		result = !(((NI)((*t).Bits[((NI)((NU32)(u) >> (NU32)(5)))- 0] & (NI)((NU32)(1) << (NU32)(((NI) ((NI)(u & 31)))))) == 0));
	}
	goto LA1;
	LA3: ;
	{
		result = NIM_FALSE;
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, freecycliccell_63227)(tgcheap46816* gch, tcell44733* c) {
	preparedealloc_49008(c);
	rawdealloc_40423((&(*gch).Region), ((void*) (c)));
}

N_NIMCALL(void, collectwhite_64604)(tcell44733* s) {
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC5;
		LOC3 = 0;
		LOC3 = (((NI) ((NI)((*s).Refcount & 3))) == 2);
		if (!(LOC3)) goto LA4;
		LOC5 = 0;
		LOC5 = contains_45423(gch_46844.Cycleroots, s);
		LOC3 = !(LOC5);
		LA4: ;
		if (!LOC3) goto LA6;
		(*s).Refcount = (NI)((*s).Refcount & -4);
		forallchildren_48817(s, ((NU8) 8));
		freecycliccell_63227((&gch_46844), s);
	}
	LA6: ;
}

N_NIMCALL(void, dooperation_48821)(void* p, NU8 op) {
	tcell44733* c;
	{
		if (!(p == NIM_NIL)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	c = usrtocell_48446(p);
	switch (op) {
	case ((NU8) 2):
	{
		decref_50404(c);
	}
	break;
	case ((NU8) 3):
	{
		add_44821((&gch_46844.Tempstack), c);
	}
	break;
	case ((NU8) 4):
	{
		(*c).Refcount = (NI)((NU32)((*c).Refcount) - (NU32)(8));
	}
	break;
	case ((NU8) 5):
	{
		(*c).Refcount = (NI)((NU32)((*c).Refcount) - (NU32)(8));
		markgray_64005(c);
	}
	break;
	case ((NU8) 6):
	{
		scan_64404(c);
	}
	break;
	case ((NU8) 7):
	{
		(*c).Refcount = (NI)((NU32)((*c).Refcount) + (NU32)(8));
		{
			if (!!((((NI) ((NI)((*c).Refcount & 3))) == 0))) goto LA13;
			scanblack_64204(c);
		}
		LA13: ;
	}
	break;
	case ((NU8) 8):
	{
		collectwhite_64604(c);
	}
	break;
	case ((NU8) 0):
	{
	}
	break;
	case ((NU8) 1):
	{
	}
	break;
	}
	BeforeRet: ;
}

N_NIMCALL(NI, getdiscriminant_25136)(void* aa, TNimNode* n) {
	NI result;
	NI d;
	NI a;
	result = 0;
	d = 0;
	a = ((NI) (aa));
	switch ((*(*n).typ).size) {
	case 1:
	{
		d = ((NI)(NU)(NU8)((*((NI8*) ((NI)((NU32)(a) + (NU32)((*n).offset)))))));
	}
	break;
	case 2:
	{
		d = ((NI)(NU)(NU16)((*((NI16*) ((NI)((NU32)(a) + (NU32)((*n).offset)))))));
	}
	break;
	case 4:
	{
		d = ((NI) ((*((NI32*) ((NI)((NU32)(a) + (NU32)((*n).offset)))))));
	}
	break;
	default:
	{
	}
	break;
	}
	result = d;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(TNimNode*, selectbranch_25410)(void* aa, TNimNode* n) {
	TNimNode* result;
	NI discr;
	result = 0;
	discr = getdiscriminant_25136(aa, n);
	{
		if (!((NU32)(discr) < (NU32)((*n).len))) goto LA3;
		result = (*n).sons[(discr)- 0];
		{
			if (!(result == NIM_NIL)) goto LA7;
			result = (*n).sons[((*n).len)- 0];
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		result = (*n).sons[((*n).len)- 0];
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, forallslotsaux_53008)(void* dest, TNimNode* n, NU8 op) {
	NI d;
	d = ((NI) (dest));
	switch ((*n).kind) {
	case ((NU8) 1):
	{
		forallchildrenaux_48825(((void*) ((NI)((NU32)(d) + (NU32)((*n).offset)))), (*n).typ, op);
	}
	break;
	case ((NU8) 2):
	{
		{
			NI i_53034;
			NI HEX3Atmp_53206;
			NI res_53209;
			i_53034 = 0;
			HEX3Atmp_53206 = 0;
			HEX3Atmp_53206 = (NI32)((*n).len - 1);
			res_53209 = 0;
			{
				while (1) {
					if (!(res_53209 <= HEX3Atmp_53206)) goto LA5;
					i_53034 = res_53209;
					{
						if (!((*(*n).sons[(i_53034)- 0]).kind == ((NU8) 1))) goto LA8;
						{
							if (!((*(*(*n).sons[(i_53034)- 0]).typ).kind == ((NU8) 22) || (*(*(*n).sons[(i_53034)- 0]).typ).kind == ((NU8) 28) || (*(*(*n).sons[(i_53034)- 0]).typ).kind == ((NU8) 24))) goto LA12;
							dooperation_48821((*((void**) ((NI)((NU32)(d) + (NU32)((*(*n).sons[(i_53034)- 0]).offset))))), op);
						}
						goto LA10;
						LA12: ;
						{
							forallchildrenaux_48825(((void*) ((NI)((NU32)(d) + (NU32)((*(*n).sons[(i_53034)- 0]).offset)))), (*(*n).sons[(i_53034)- 0]).typ, op);
						}
						LA10: ;
					}
					goto LA6;
					LA8: ;
					{
						forallslotsaux_53008(dest, (*n).sons[(i_53034)- 0], op);
					}
					LA6: ;
					res_53209 += 1;
				} LA5: ;
			}
		}
	}
	break;
	case ((NU8) 3):
	{
		TNimNode* m;
		m = selectbranch_25410(dest, n);
		{
			if (!!((m == NIM_NIL))) goto LA19;
			forallslotsaux_53008(dest, m, op);
		}
		LA19: ;
	}
	break;
	case ((NU8) 0):
	{
	}
	break;
	}
}

N_NIMCALL(void, forallchildrenaux_48825)(void* dest, TNimType* mt, NU8 op) {
	NI d;
	d = ((NI) (dest));
	{
		if (!(dest == NIM_NIL)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	{
		if (!!((((*mt).flags &(1<<((((NU8) 0))&7)))!=0))) goto LA7;
		switch ((*mt).kind) {
		case ((NU8) 22):
		case ((NU8) 28):
		case ((NU8) 24):
		{
			dooperation_48821((*((void**) (d))), op);
		}
		break;
		case ((NU8) 17):
		case ((NU8) 18):
		{
			forallslotsaux_53008(dest, (*mt).node, op);
		}
		break;
		case ((NU8) 16):
		case ((NU8) 4):
		case ((NU8) 27):
		{
			{
				NI i_53252;
				NI HEX3Atmp_53275;
				NI res_53278;
				i_53252 = 0;
				HEX3Atmp_53275 = 0;
				HEX3Atmp_53275 = (NI32)((NI32)((*mt).size / (*(*mt).base).size) - 1);
				res_53278 = 0;
				{
					while (1) {
						if (!(res_53278 <= HEX3Atmp_53275)) goto LA14;
						i_53252 = res_53278;
						forallchildrenaux_48825(((void*) ((NI)((NU32)(d) + (NU32)((NI)((NU32)(i_53252) * (NU32)((*(*mt).base).size)))))), (*mt).base, op);
						res_53278 += 1;
					} LA14: ;
				}
			}
		}
		break;
		default:
		{
		}
		break;
		}
	}
	LA7: ;
	BeforeRet: ;
}

N_NIMCALL(void, forallchildren_48817)(tcell44733* cell, NU8 op) {
	TY3089 marker;
	marker = (*(*cell).Typ).marker;
	{
		void* LOC5;
		if (!!((marker == NIM_NIL))) goto LA3;
		LOC5 = 0;
		LOC5 = celltousr_48425(cell);
		marker(LOC5, ((NI) (op)));
	}
	goto LA1;
	LA3: ;
	{
		switch ((*(*cell).Typ).kind) {
		case ((NU8) 22):
		{
			void* LOC8;
			LOC8 = 0;
			LOC8 = celltousr_48425(cell);
			forallchildrenaux_48825(LOC8, (*(*cell).Typ).base, op);
		}
		break;
		case ((NU8) 24):
		{
			NI d;
			void* LOC10;
			TGenericSeq* s;
			LOC10 = 0;
			LOC10 = celltousr_48425(cell);
			d = ((NI) (LOC10));
			s = ((TGenericSeq*) (d));
			{
				if (!!((s == NIM_NIL))) goto LA13;
				{
					NI i_54040;
					NI HEX3Atmp_54073;
					NI res_54076;
					i_54040 = 0;
					HEX3Atmp_54073 = 0;
					HEX3Atmp_54073 = (NI32)((*s).len - 1);
					res_54076 = 0;
					{
						while (1) {
							if (!(res_54076 <= HEX3Atmp_54073)) goto LA17;
							i_54040 = res_54076;
							forallchildrenaux_48825(((void*) ((NI)((NU32)((NI)((NU32)(d) + (NU32)((NI)((NU32)(i_54040) * (NU32)((*(*(*cell).Typ).base).size))))) + (NU32)(8)))), (*(*cell).Typ).base, op);
							res_54076 += 1;
						} LA17: ;
					}
				}
			}
			LA13: ;
		}
		break;
		default:
		{
		}
		break;
		}
	}
	LA1: ;
}

N_NIMCALL(NIM_BOOL, collectzct_66812)(tgcheap46816* gch) {
	NIM_BOOL result;
	NI* l;
	result = 0;
	l = (&(*gch).Zct.Len);
	{
		while (1) {
			tcell44733* c;
			if (!(0 < (*l))) goto LA2;
			c = (*gch).Zct.D[(0)- 0];
			(*c).Refcount = (NI)((*c).Refcount & -5);
			(*gch).Zct.D[(0)- 0] = (*gch).Zct.D[((NI32)((*l) - 1))- 0];
			(*l) -= 1;
			{
				if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA5;
				{
					NIM_BOOL LOC9;
					LOC9 = 0;
					LOC9 = canbecycleroot_48467(c);
					if (!LOC9) goto LA10;
					excl_45502((&(*gch).Cycleroots), c);
				}
				LA10: ;
				preparedealloc_49008(c);
				forallchildren_48817(c, ((NU8) 2));
				rawdealloc_40423((&(*gch).Region), ((void*) (c)));
			}
			LA5: ;
		} LA2: ;
	}
	result = NIM_TRUE;
	return result;
}

N_NIMCALL(void, markroots_64805)(tgcheap46816* gch) {
	NI tabsize;
	tabsize = 0;
	{
		tcell44733* s_64810;
		tcellset44745 HEX3Atmp_64839;
		tpagedesc44741* r_64844;
		s_64810 = 0;
		memset((void*)(&HEX3Atmp_64839), 0, sizeof(HEX3Atmp_64839));
		HEX3Atmp_64839 = (*gch).Cycleroots;
		r_64844 = HEX3Atmp_64839.Head;
		{
			while (1) {
				NI i_64846;
				if (!!((r_64844 == NIM_NIL))) goto LA3;
				i_64846 = 0;
				{
					while (1) {
						NI w_64848;
						NI j_64850;
						if (!(i_64846 <= 15)) goto LA5;
						w_64848 = (*r_64844).Bits[(i_64846)- 0];
						j_64850 = 0;
						{
							while (1) {
								if (!!((w_64848 == 0))) goto LA7;
								{
									if (!!((((NI) ((NI)(w_64848 & 1))) == 0))) goto LA10;
									s_64810 = ((tcell44733*) ((NI)((NI)((NU32)((*r_64844).Key) << (NU32)(12)) | (NI)((NU32)((NI)((NU32)((NI)((NU32)(i_64846) << (NU32)(5))) + (NU32)(j_64850))) * (NU32)(8)))));
									tabsize += 1;
									{
										NIM_BOOL LOC14;
										LOC14 = 0;
										LOC14 = (((NI) ((NI)((*s_64810).Refcount & 3))) == 3);
										if (!(LOC14)) goto LA15;
										LOC14 = ((NU32)(8) <= (NU32)((*s_64810).Refcount));
										LA15: ;
										if (!LOC14) goto LA16;
										markgray_64005(s_64810);
									}
									goto LA12;
									LA16: ;
									{
										excl_45502((&(*gch).Cycleroots), s_64810);
										{
											if (!((*s_64810).Refcount == 0)) goto LA21;
											freecycliccell_63227(gch, s_64810);
										}
										LA21: ;
									}
									LA12: ;
								}
								LA10: ;
								j_64850 += 1;
								w_64848 = (NI)((NU32)(w_64848) >> (NU32)(1));
							} LA7: ;
						}
						i_64846 += 1;
					} LA5: ;
				}
				r_64844 = (*r_64844).Next;
			} LA3: ;
		}
	}
	(*gch).Stat.Cycletablesize = (((*gch).Stat.Cycletablesize >= tabsize) ? (*gch).Stat.Cycletablesize : tabsize);
}

N_NIMCALL(void, collectroots_67001)(tgcheap46816* gch) {
	{
		tcell44733* s_67005;
		tcellset44745 HEX3Atmp_67008;
		tpagedesc44741* r_67013;
		s_67005 = 0;
		memset((void*)(&HEX3Atmp_67008), 0, sizeof(HEX3Atmp_67008));
		HEX3Atmp_67008 = (*gch).Cycleroots;
		r_67013 = HEX3Atmp_67008.Head;
		{
			while (1) {
				NI i_67015;
				if (!!((r_67013 == NIM_NIL))) goto LA3;
				i_67015 = 0;
				{
					while (1) {
						NI w_67017;
						NI j_67019;
						if (!(i_67015 <= 15)) goto LA5;
						w_67017 = (*r_67013).Bits[(i_67015)- 0];
						j_67019 = 0;
						{
							while (1) {
								if (!!((w_67017 == 0))) goto LA7;
								{
									if (!!((((NI) ((NI)(w_67017 & 1))) == 0))) goto LA10;
									s_67005 = ((tcell44733*) ((NI)((NI)((NU32)((*r_67013).Key) << (NU32)(12)) | (NI)((NU32)((NI)((NU32)((NI)((NU32)(i_67015) << (NU32)(5))) + (NU32)(j_67019))) * (NU32)(8)))));
									excl_45502((&(*gch).Cycleroots), s_67005);
									collectwhite_64604(s_67005);
								}
								LA10: ;
								j_67019 += 1;
								w_67017 = (NI)((NU32)(w_67017) >> (NU32)(1));
							} LA7: ;
						}
						i_67015 += 1;
					} LA5: ;
				}
				r_67013 = (*r_67013).Next;
			} LA3: ;
		}
	}
}

N_NIMCALL(void, deinit_44879)(tcellset44745* s) {
	tpagedesc44741* it;
	it = (*s).Head;
	{
		while (1) {
			tpagedesc44741* n;
			if (!!((it == NIM_NIL))) goto LA2;
			n = (*it).Next;
			dealloc_5848(((void*) (it)));
			it = n;
		} LA2: ;
	}
	(*s).Head = NIM_NIL;
	dealloc_5848(((void*) ((*s).Data)));
	(*s).Data = NIM_NIL;
	(*s).Counter = 0;
}

N_NIMCALL(void, cellsetreset_53001)(tcellset44745* s) {
	deinit_44879(s);
	init_44868(s);
}

N_NIMCALL(void, collectcycles_67045)(tgcheap46816* gch) {
	{
		while (1) {
			NIM_BOOL LOC3;
			if (!(0 < (*gch).Zct.Len)) goto LA2;
			LOC3 = 0;
			LOC3 = collectzct_66812(gch);
		} LA2: ;
	}
	markroots_64805(gch);
	{
		tcell44733* s_67201;
		tcellset44745 HEX3Atmp_67403;
		tpagedesc44741* r_67408;
		s_67201 = 0;
		memset((void*)(&HEX3Atmp_67403), 0, sizeof(HEX3Atmp_67403));
		HEX3Atmp_67403 = (*gch).Cycleroots;
		r_67408 = HEX3Atmp_67403.Head;
		{
			while (1) {
				NI i_67410;
				if (!!((r_67408 == NIM_NIL))) goto LA6;
				i_67410 = 0;
				{
					while (1) {
						NI w_67412;
						NI j_67414;
						if (!(i_67410 <= 15)) goto LA8;
						w_67412 = (*r_67408).Bits[(i_67410)- 0];
						j_67414 = 0;
						{
							while (1) {
								if (!!((w_67412 == 0))) goto LA10;
								{
									if (!!((((NI) ((NI)(w_67412 & 1))) == 0))) goto LA13;
									s_67201 = ((tcell44733*) ((NI)((NI)((NU32)((*r_67408).Key) << (NU32)(12)) | (NI)((NU32)((NI)((NU32)((NI)((NU32)(i_67410) << (NU32)(5))) + (NU32)(j_67414))) * (NU32)(8)))));
									scan_64404(s_67201);
								}
								LA13: ;
								j_67414 += 1;
								w_67412 = (NI)((NU32)(w_67412) >> (NU32)(1));
							} LA10: ;
						}
						i_67410 += 1;
					} LA8: ;
				}
				r_67408 = (*r_67408).Next;
			} LA6: ;
		}
	}
	collectroots_67001(gch);
	cellsetreset_53001((&(*gch).Cycleroots));
}

N_NIMCALL(NI, gettotalmem_6499)(void) {
	NI result;
	result = 0;
	result = gch_46844.Region.Currmem;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getfreemem_6497)(void) {
	NI result;
	result = 0;
	result = gch_46844.Region.Freemem;
	return result;
}

N_NIMCALL(NI, getoccupiedmem_6495)(void) {
	NI result;
	NI LOC1;
	NI LOC2;
	result = 0;
	LOC1 = 0;
	LOC1 = gettotalmem_6499();
	LOC2 = 0;
	LOC2 = getfreemem_6497();
	result = (NI32)(LOC1 - LOC2);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, unmarkstackandregisters_71211)(tgcheap46816* gch) {
	tcell44733** d;
	d = (*gch).Decstack.D;
	{
		NI i_71226;
		NI HEX3Atmp_71402;
		NI res_71405;
		i_71226 = 0;
		HEX3Atmp_71402 = 0;
		HEX3Atmp_71402 = (NI32)((*gch).Decstack.Len - 1);
		res_71405 = 0;
		{
			while (1) {
				if (!(res_71405 <= HEX3Atmp_71402)) goto LA3;
				i_71226 = res_71405;
				decref_50404(d[(i_71226)- 0]);
				res_71405 += 1;
			} LA3: ;
		}
	}
	(*gch).Decstack.Len = 0;
}

N_NIMCALL(void, collectctbody_71419)(tgcheap46816* gch) {
	NI LOC1;
	LOC1 = 0;
	LOC1 = stacksize_68810();
	(*gch).Stat.Maxstacksize = (((*gch).Stat.Maxstacksize >= LOC1) ? (*gch).Stat.Maxstacksize : LOC1);
	prepareforinteriorpointerchecking_42082((&(*gch).Region));
	markstackandregisters_69040(gch);
	markthreadstacks_68006(gch);
	(*gch).Stat.Maxstackcells = (((*gch).Stat.Maxstackcells >= (*gch).Decstack.Len) ? (*gch).Stat.Maxstackcells : (*gch).Decstack.Len);
	(*gch).Stat.Stackscans += 1;
	{
		NIM_BOOL LOC4;
		LOC4 = 0;
		LOC4 = collectzct_66812(gch);
		if (!LOC4) goto LA5;
		{
			NIM_BOOL LOC9;
			NI LOC10;
			NI LOC14;
			LOC9 = 0;
			LOC10 = 0;
			LOC10 = getoccupiedmem_44668((&(*gch).Region));
			LOC9 = ((*gch).Cyclethreshold <= LOC10);
			if (LOC9) goto LA11;
			LOC9 = NIM_FALSE;
			LA11: ;
			if (!LOC9) goto LA12;
			collectcycles_67045(gch);
			(*gch).Stat.Cyclecollections += 1;
			LOC14 = 0;
			LOC14 = getoccupiedmem_6495();
			(*gch).Cyclethreshold = ((4194304 >= (NI32)(LOC14 * 2)) ? 4194304 : (NI32)(LOC14 * 2));
			(*gch).Stat.Maxthreshold = (((*gch).Stat.Maxthreshold >= (*gch).Cyclethreshold) ? (*gch).Stat.Maxthreshold : (*gch).Cyclethreshold);
		}
		LA12: ;
	}
	LA5: ;
	unmarkstackandregisters_71211(gch);
}

N_NIMCALL(void, collectct_48810)(tgcheap46816* gch) {
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		NIM_BOOL LOC5;
		NIM_BOOL LOC7;
		NI LOC9;
		LOC3 = 0;
		LOC4 = 0;
		LOC5 = 0;
		LOC5 = (500 <= (*gch).Zct.Len);
		if (LOC5) goto LA6;
		LOC7 = 0;
		LOC7 = NIM_TRUE;
		if (!(LOC7)) goto LA8;
		LOC9 = 0;
		LOC9 = getoccupiedmem_44668((&(*gch).Region));
		LOC7 = ((*gch).Cyclethreshold <= LOC9);
		LA8: ;
		LOC5 = LOC7;
		LA6: ;
		LOC4 = LOC5;
		if (LOC4) goto LA10;
		LOC4 = NIM_FALSE;
		LA10: ;
		LOC3 = LOC4;
		if (!(LOC3)) goto LA11;
		LOC3 = ((*gch).Recgclock == 0);
		LA11: ;
		if (!LOC3) goto LA12;
		collectctbody_71419(gch);
	}
	LA12: ;
}

static N_INLINE(void, addnewobjtozct_54090)(tcell44733* res, tgcheap46816* gch) {
	NI l;
	tcell44733** d;
	l = (*gch).Zct.Len;
	d = (*gch).Zct.D;
	{
		tcell44733* c;
		if (!(8 < l)) goto LA3;
		c = 0;
		c = d[((NI32)(l - 1))- 0];
		{
			if (!((NU32)(8) <= (NU32)((*c).Refcount))) goto LA7;
			(*c).Refcount = (NI)((*c).Refcount & -5);
			d[((NI32)(l - 1))- 0] = res;
			goto BeforeRet;
		}
		LA7: ;
		c = d[((NI32)(l - 2))- 0];
		{
			if (!((NU32)(8) <= (NU32)((*c).Refcount))) goto LA11;
			(*c).Refcount = (NI)((*c).Refcount & -5);
			d[((NI32)(l - 2))- 0] = res;
			goto BeforeRet;
		}
		LA11: ;
		c = d[((NI32)(l - 3))- 0];
		{
			if (!((NU32)(8) <= (NU32)((*c).Refcount))) goto LA15;
			(*c).Refcount = (NI)((*c).Refcount & -5);
			d[((NI32)(l - 3))- 0] = res;
			goto BeforeRet;
		}
		LA15: ;
		c = d[((NI32)(l - 4))- 0];
		{
			if (!((NU32)(8) <= (NU32)((*c).Refcount))) goto LA19;
			(*c).Refcount = (NI)((*c).Refcount & -5);
			d[((NI32)(l - 4))- 0] = res;
			goto BeforeRet;
		}
		LA19: ;
		c = d[((NI32)(l - 5))- 0];
		{
			if (!((NU32)(8) <= (NU32)((*c).Refcount))) goto LA23;
			(*c).Refcount = (NI)((*c).Refcount & -5);
			d[((NI32)(l - 5))- 0] = res;
			goto BeforeRet;
		}
		LA23: ;
		c = d[((NI32)(l - 6))- 0];
		{
			if (!((NU32)(8) <= (NU32)((*c).Refcount))) goto LA27;
			(*c).Refcount = (NI)((*c).Refcount & -5);
			d[((NI32)(l - 6))- 0] = res;
			goto BeforeRet;
		}
		LA27: ;
		c = d[((NI32)(l - 7))- 0];
		{
			if (!((NU32)(8) <= (NU32)((*c).Refcount))) goto LA31;
			(*c).Refcount = (NI)((*c).Refcount & -5);
			d[((NI32)(l - 7))- 0] = res;
			goto BeforeRet;
		}
		LA31: ;
		c = d[((NI32)(l - 8))- 0];
		{
			if (!((NU32)(8) <= (NU32)((*c).Refcount))) goto LA35;
			(*c).Refcount = (NI)((*c).Refcount & -5);
			d[((NI32)(l - 8))- 0] = res;
			goto BeforeRet;
		}
		LA35: ;
		add_44821((&(*gch).Zct), res);
	}
	goto LA1;
	LA3: ;
	{
		d[(l)- 0] = res;
		(*gch).Zct.Len += 1;
	}
	LA1: ;
	BeforeRet: ;
}

N_NIMCALL(void*, rawnewobj_54604)(TNimType* typ, NI size, tgcheap46816* gch) {
	void* result;
	tcell44733* res;
	void* LOC1;
	result = 0;
	collectct_48810(gch);
	LOC1 = 0;
	LOC1 = rawalloc_34146((&(*gch).Region), (NI32)(size + ((NI)sizeof(tcell44733))));
	res = ((tcell44733*) (LOC1));
	(*res).Typ = typ;
	(*res).Refcount = 4;
	addnewobjtozct_54090(res, gch);
	result = celltousr_48425(res);
	return result;
}

N_NIMCALL(void*, newObj)(TNimType* typ, NI size) {
	void* result;
	result = 0;
	result = rawnewobj_54604(typ, size, (&gch_46844));
	zeroMem(result, size);
	return result;
}

N_NIMCALL(NimStringDesc*, rawNewString)(NI space) {
	NimStringDesc* result;
	NI s;
	void* LOC5;
	result = 0;
	s = space;
	{
		if (!(s < 8)) goto LA3;
		s = 7;
	}
	LA3: ;
	LOC5 = 0;
	LOC5 = newObj((&strdesc_9804), (NI32)((NI32)(((NI)sizeof(TGenericSeq)) + s) + 1));
	result = ((NimStringDesc*) (LOC5));
	(*result).Sup.reserved = s;
	return result;
}

N_NIMCALL(NimStringDesc*, toNimStr)(NCSTRING str, NI len) {
	NimStringDesc* result;
	result = 0;
	result = rawNewString(len);
	(*result).Sup.len = len;
	memcpy(((NCSTRING) ((*result).data)), str, (NI32)((NI32)(len + 1) * 1));
	return result;
}

N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str) {
	NimStringDesc* result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = strlen(str);
	result = toNimStr(str, LOC1);
	return result;
}

N_NIMCALL(void, write_12877)(FILE* f, NCSTRING c) {
	fputs(c, f);
}

N_NIMCALL(void, writetostderr_16201)(NCSTRING msg) {
	write_12877(stderr, msg);
}

N_NIMCALL(void, showerrormessage_16209)(NCSTRING data) {
	{
		NimStringDesc* LOC5;
		if (!!((errormessagewriter_16004 == NIM_NIL))) goto LA3;
		LOC5 = 0;
		LOC5 = cstrToNimstr(data);
		errormessagewriter_16004(LOC5);
	}
	goto LA1;
	LA3: ;
	{
		writetostderr_16201(data);
	}
	LA1: ;
}

N_NOCONV(void, signalHandler)(int sig) {
	NCSTRING msg;
	msg = 0;
	{
		if (!(sig == SIGINT)) goto LA3;
		msg = "SIGINT: Interrupted by Ctrl-C.\015\012";
	}
	goto LA1;
	LA3: ;
	{
		if (!(sig == SIGSEGV)) goto LA6;
		msg = "SIGSEGV: Illegal storage access. (Try to compile with -d:useSys"
"Assert -d:useGcAssert for details.)\015\012";
	}
	goto LA1;
	LA6: ;
	{
		if (!(sig == SIGABRT)) goto LA9;
		msg = "SIGABRT: Abnormal termination.\015\012";
	}
	goto LA1;
	LA9: ;
	{
		if (!(sig == SIGFPE)) goto LA12;
		msg = "SIGFPE: Arithmetic error.\015\012";
	}
	goto LA1;
	LA12: ;
	{
		if (!(sig == SIGILL)) goto LA15;
		msg = "SIGILL: Illegal operation.\015\012";
	}
	goto LA1;
	LA15: ;
	{
		if (!(sig == SIGSEGV)) goto LA18;
		msg = "SIGBUS: Illegal storage access.  (Try to compile with -d:useSys"
"Assert -d:useGcAssert for details.)\015\012";
	}
	goto LA1;
	LA18: ;
	{
		{
			msg = "unknown signal\015\012";
		}
	}
	LA1: ;
	showerrormessage_16209(msg);
	exit(1);
}

N_NIMCALL(void, registersignalhandler_19808)(void) {
	signal(SIGINT, signalHandler);
	signal(SIGSEGV, signalHandler);
	signal(SIGABRT, signalHandler);
	signal(SIGFPE, signalHandler);
	signal(SIGILL, signalHandler);
	signal(SIGSEGV, signalHandler);
}

N_NIMCALL(NI, getRefcount)(void* p) {
	NI result;
	tcell44733* LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = usrtocell_48446(p);
	result = (NI)((NU32)((*LOC1).Refcount) >> (NU32)(3));
	return result;
}
NIM_EXTERNC N_NOINLINE(void, systemInit)(void) {
	NI LOC1;
	NI LOC2;
	strdesc_9804.size = 4;
	strdesc_9804.kind = ((NU8) 28);
	strdesc_9804.flags = 2;
	LOC1 = 0;
	LOC1 = fileno(stdin);
	setmode(LOC1, O_BINARY);
	LOC2 = 0;
	LOC2 = fileno(stdout);
	setmode(LOC2, O_BINARY);
	initallocator_9401();
	initStackBottom();
	initgc_9201();
	registersignalhandler_19808();
}

NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void) {
}

