/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -O3 -fno-strict-aliasing  -IC:\App\native-toolchain\nim-0.10.2\lib -o c:\users\nigahachi\desktop\projectc\nim\nimcache\prg02.o c:\users\nigahachi\desktop\projectc\nim\nimcache\prg02.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <stdio.h>
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, readline_12886)(FILE* f);
N_NIMCALL(NI, nosexecShellCmd)(NimStringDesc* command);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_parseutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_strutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_winleanInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_winleanDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_timesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_osDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, prg02Init)(void);
NIM_EXTERNC N_NOINLINE(void, prg02DatInit)(void);
STRING_LITERAL(TMP17, "A number please: ", 17);
STRING_LITERAL(TMP33, "The number is in the set: {0, 1, 2, 4, 5, 6, 7}", 47);
STRING_LITERAL(TMP34, "The number is 3 or 8", 20);
STRING_LITERAL(TMP35, "pause", 5);
NI n_128011;

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	HEX00_parseutilsDatInit();
	HEX00_strutilsDatInit();
	HEX00_winleanDatInit();
	HEX00_timesDatInit();
	HEX00_osDatInit();
	prg02DatInit();
	HEX00_parseutilsInit();
	HEX00_strutilsInit();
	HEX00_winleanInit();
	HEX00_timesInit();
	HEX00_osInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	prg02Init();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, prg02Init)(void) {
	NimStringDesc* LOC1;
	NI LOC5;
	printf("%s\015\012", (((NimStringDesc*) &TMP17))->data);
	LOC1 = 0;
	LOC1 = readline_12886(stdin);
	n_128011 = nsuParseInt(LOC1);
	switch (n_128011) {
	case 0 ... 2:
	case 4 ... 7:
	{
		printf("%s\015\012", (((NimStringDesc*) &TMP33))->data);
	}
	break;
	case 3:
	case 8:
	{
		printf("%s\015\012", (((NimStringDesc*) &TMP34))->data);
	}
	break;
	default:
	{
	}
	break;
	}
	LOC5 = 0;
	LOC5 = nosexecShellCmd(((NimStringDesc*) &TMP35));
}

NIM_EXTERNC N_NOINLINE(void, prg02DatInit)(void) {
}

